version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: db_stacklab_identity_guard
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_stacklab_identity_guard
      TZ: Asia/Jakarta
    ports:
      - "3306:3306"
    volumes:
      - ../sql/init.sql:/docker-entrypoint-initdb.d/init.sql